-- 
-- STAR LOCATIONS
-- 


-- -- -----------------------------
-- -- MOVE PLANET LOCATIONS INSIDE OF CALIDUS
-- -- -----------------------------

-- -- Put Gleba south of Nauvis
-- PlanetsLib:update({
-- 	{
-- 		type = "planet",
-- 		name = "gleba",
-- 		orbit = {
-- 			parent = {
-- 				type = "space-location",
-- 				name = "star",
-- 			},
-- 			distance = 20,
-- 			orientation = 0.35,
-- 			sprite = {
--                 type = "sprite",
--                 filename = "__razi-protocol__/graphics/orbits/orbit_20.png",
--                 size = 1638,
--             },
-- 		},
-- 	},
-- })

-- -- Put Arig south of Nauvis
-- PlanetsLib:update({
-- 	{
-- 		type = "planet",
-- 		name = "arig",
-- 		orbit = {
-- 			parent = {
-- 				type = "space-location",
-- 				name = "star",
-- 			},
-- 			distance = 20,
-- 			orientation = 0.4,
-- 			sprite = {
--                 type = "sprite",
--                 filename = "__razi-protocol__/graphics/orbits/orbit_11.png",
--                 size = 901,
--             },
-- 		},
-- 	},
-- })



-- -- -----------------------------
-- -- MOVE PLANET LOCATIONS INSIDE OF NYXARIS
-- -- -----------------------------

-- -- Put Corrundum to Nyxaris
-- PlanetsLib:update({
-- 	{
-- 		type = "planet",
-- 		name = "corrundum",
-- 		orbit = {
-- 			parent = {
-- 				type = "space-location",
-- 				name = "nyxaris",
-- 			},
-- 			distance = 18,
-- 			orientation = 0.2,
-- 			sprite = {
--                 type = "sprite",
--                 filename = "__razi-protocol__/graphics/orbits/orbit_18.png",
--                 size = 1475,
--             },
-- 		},
-- 	},
-- })

-- -- Put Vulcanus to Nyxaris
-- PlanetsLib:update({
-- 	{
-- 		type = "planet",
-- 		name = "vulcanus",
-- 		orbit = {
-- 			parent = {
-- 				type = "space-location",
-- 				name = "nyxaris",
-- 			},
-- 			distance = 12,
-- 			orientation = 0.75,
-- 			sprite = {
--                 type = "sprite",
--                 filename = "__razi-protocol__/graphics/orbits/orbit_12.png",
--                 size = 983,
--             },
-- 		},
-- 	},
-- })

-- -- Put Panglia to Nyxaris
-- PlanetsLib:update({
-- 	{
-- 		type = "planet",
-- 		name = "panglia",
-- 		orbit = {
-- 			parent = {
-- 				type = "space-location",
-- 				name = "nyxaris",
-- 			},
-- 			distance = 19,
-- 			orientation = 0.38,
-- 			sprite = {
--                 type = "sprite",
--                 filename = "__razi-protocol__/graphics/orbits/orbit_19.png",
--                 size = 1556,
--             },
-- 		},
-- 	},
-- })

-- -- Put Moshine to nyxaris
-- PlanetsLib:update({
-- 	{
-- 		type = "planet",
-- 		name = "moshine",
-- 		orbit = {
-- 			parent = {
-- 				type = "space-location",
-- 				name = "nyxaris",
-- 			},
-- 			distance = 6,
-- 			orientation = 0.91,
-- 			sprite = {
--                 type = "sprite",
--                 filename = "__razi-protocol__/graphics/orbits/orbit_6.png",
--                 size = 492,
--             },
-- 		},
-- 	},
-- })

-- -- Move Tellus to nyxaris
-- PlanetsLib:update({
-- 	type = "planet",
-- 	name = "tellus",
-- 	orbit = {
-- 		parent = {
-- 			type = "space-location",
-- 			name = "nyxaris",
-- 		},
-- 		distance = 18,
-- 		orientation = 0.55,
-- 		sprite = {
-- 			type = "sprite",
-- 			filename = "__razi-protocol__/graphics/orbits/orbit_18.png",
-- 			size = 1475,
-- 		},
-- 	},
-- })

-- -- Move Cubium to Solaris
-- PlanetsLib:update({
-- 	type = "planet",
-- 	name = "cubium",
-- 	orbit = {
-- 		parent = {
-- 			type = "space-location",
-- 			name = "solaris",
-- 		},
-- 		distance = 25,
-- 		orientation = 1.15,
-- 		sprite = {
-- 			type = "sprite",
-- 			filename = "__razi-protocol__/graphics/orbits/orbit_25.png",
-- 			size = 2048,
-- 		},
-- 	},
-- })

-- -- -----------------------------
-- -- MOVE PLANET LOCATIONS INSIDE OF SOLARIS
-- -- -----------------------------

-- -- Move Maraxsis to Solaris
-- PlanetsLib:update({
-- 	type = "planet",
-- 	name = "maraxsis",
-- 	orbit = {
-- 		parent = {
-- 			type = "space-location",
-- 			name = "solaris",
-- 		},
-- 		distance = 25,
-- 		orientation = 0.25,
-- 		sprite = {
-- 			type = "sprite",
-- 			filename = "__razi-protocol__/graphics/orbits/orbit_25.png",
-- 			size = 2048,
-- 		},
-- 	},
-- })

-- -- Move Pelagos to Solaris
-- PlanetsLib:update({
-- 	type = "planet",
-- 	name = "pelagos",
-- 	orbit = {
-- 		parent = {
-- 			type = "space-location",
-- 			name = "solaris",
-- 		},
-- 		distance = 25,
-- 		orientation = 1.3,
-- 		sprite = {
-- 			type = "sprite",
-- 			filename = "__razi-protocol__/graphics/orbits/orbit_25.png",
-- 			size = 2048,
-- 		},
-- 	},
-- })

-- -- Move Hyarion to Solaris
-- PlanetsLib:update({
-- 	type = "planet",
-- 	name = "hyarion",
-- 	orbit = {
-- 		parent = {
-- 			type = "space-location",
-- 			name = "solaris",
-- 		},
-- 		distance = 20,
-- 		orientation = 0.85,
-- 		sprite = {
-- 			type = "sprite",
-- 			filename = "__razi-protocol__/graphics/orbits/orbit_20.png",
-- 			size = 1638,
-- 		},
-- 	},
-- })

-- -- Move Tenebris to Solaris
-- PlanetsLib:update({
-- 	type = "planet",
-- 	name = "tenebris",
-- 	orbit = {
-- 		parent = {
-- 			type = "space-location",
-- 			name = "solaris",
-- 		},
-- 		distance = 32,
-- 		orientation = 0.75,
-- 		sprite = {
-- 			type = "sprite",
-- 			filename = "__razi-protocol__/graphics/orbits/orbit_32.png",
-- 			size = 2621,
-- 		},
-- 	},
-- })

-- -- -----------------------------
-- -- MOVE PLANET LOCATIONS INSIDE OF BEETLEJUICE
-- -- -----------------------------

-- -- Move apia-carnova-orbit to BeetleJuice
-- PlanetsLib:update({
-- 	type = "space-location",
-- 	name = "apia-carnova-orbit",
-- 	orbit = {
-- 		parent = {
-- 			type = "space-location",
-- 			name = "beetlejuice",
-- 		},
-- 		distance = 40,
-- 		orientation = 0.9,
-- 		sprite = {
-- 			type = "sprite",
-- 			filename = "__razi-protocol__/graphics/orbits/orbit_40.png",
-- 			size = 3277,
-- 		},
-- 	},
-- })


-- -- Move paracelsin to BeetleJuice
-- PlanetsLib:update({
-- 	type = "planet",
-- 	name = "paracelsin",
-- 	orbit = {
-- 		parent = {
-- 			type = "space-location",
-- 			name = "beetlejuice",
-- 		},
-- 		distance = 35,
-- 		orientation = 1.5,
-- 		sprite = {
-- 			type = "sprite",
-- 			filename = "__razi-protocol__/graphics/orbits/orbit_35.png",
-- 			size = 2867,
-- 		},
-- 	},
-- })


-- -- Move Secretas to BeetleJuice
-- PlanetsLib:update({
-- 	type = "space-location",
-- 	name = "secretas",
-- 	orbit = {
-- 		parent = {
-- 			type = "space-location",
-- 			name = "beetlejuice",
-- 		},
-- 		distance = 35,
-- 		orientation = 0.45,
-- 		sprite = {
-- 			type = "sprite",
-- 			filename = "__razi-protocol__/graphics/orbits/orbit_35.png",
-- 			size = 2867,
-- 		},
-- 	},
-- })

-- -- Move Frozeta to BeetleJuice
-- PlanetsLib:update({
-- 	type = "planet",
-- 	name = "frozeta",
-- 	orbit = {
-- 		parent = {
-- 			type = "space-location",
-- 			name = "secretas",
-- 		},
-- 		distance = 6,
-- 		orientation = 0.25,
-- 		sprite = {
-- 			type = "sprite",
-- 			filename = "__razi-protocol__/graphics/orbits/orbit_6.png",
-- 			size = 492,
-- 		},
-- 	},
-- })


-- -- Move shattered-planet to Beetlejuice
-- PlanetsLib:update({
-- 	type = "planet",
-- 	name = "nexus",
-- 	orbit = {
-- 		parent = {
-- 			type = "space-location",
-- 			name = "beetlejuice",
-- 		},
-- 		distance = 80,
-- 		orientation = 0.3,
-- 	},
-- })

-- -- Move black hole approach to Beetlejuice
-- PlanetsLib:update({
-- 	type = "space-location",
-- 	name = "black-hole-approach",
-- 	orbit = {
-- 		parent = {
-- 			type = "space-location",
-- 			name = "beetlejuice",
-- 		},
-- 		distance = 100,
-- 		orientation = 0.25,
-- 	},
-- })

-- -- Move black hole to Beetlejuice
-- PlanetsLib:update({
-- 	type = "space-location",
-- 	name = "black-hole",
-- 	orbit = {
-- 		parent = {
-- 			type = "space-location",
-- 			name = "beetlejuice",
-- 		},
-- 		distance = 120,
-- 		orientation = 0.25,
-- 	},
-- })
